sudo: false
language: go
go:
  - 1.8
  - 1.9
  - "1.10"
go_import_path: github.com/gonium/gosdm630
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get -u github.com/golang/dep/cmd/dep
install:
  - make dep
  - dep ensure
script:
  - make
